export {default as Welcome} from '../screens/Welcome'
export {default as Dashboard} from '../screens/dashBoard'
export {default as Search} from '../screens/Search'
export {default as Home} from '../screens/Home'
export {default as AdminDashboard} from '../components/admin/AdminDashboard'